### ISSUE TITLE
Availability.

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/RFSOC_SAWG#6]
I asked Trenz about the lead time of the modules. The RFSOC chips disappeared from the market completely. I assume we won't get it sooner than 53 weeks. The AVNET modules have prohibitive prices.

**Comment by gkasprow** [comment]
there are other alternatives
https://www.knowres.com/products4zu/
https://www.pentek.com/products/detail.cfm?model=6003

**Comment by jordens** [comment]
Might be (now or soon) impacted by export limitations. After all this is a significant component in quantum technology.

**Comment by gkasprow** [comment]
i asked for availability. They have two banks of the SDRAM

**Comment by gkasprow** [comment]
the first vendor is from EU

**Comment by gkasprow** [comment]
Trenz so far offers the best price (4.4k EUR). They accept offers

**Comment by gkasprow** [comment]
Currently we are placing the order for 2 pcs

**Comment by gkasprow** [comment]
Pentek has very good quality but for us, pricing is not acceptable; they have also IP issues.
Let's stay with Trenz.
