### ISSUE TITLE
Form factor

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/RFSOC_SAWG#9]
Dual EEM? SFP? Or maybe CPCIS RTM for apps requiring wideband communication.

**Comment by gkasprow** [comment]
DI/OT has an RTM connector foreseen. Let's route MGTs and place QSFP connectors there when higher BW is needed.

**Comment by kaolpr** [comment]
Please note that DI/OT RTM will be undergoing some changes. Guess it's mainly the length, but as it's the least specified part of DI/OT who knows ;-).

**Comment by gkasprow** [comment]
We will use Firefly connectors. Both QSFP28 and MTF options are possible
